apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      nodePort: 30888
  selector:
    app: playground
